### ISSUE TITLE
Block new occurrence row creation until an existing row is updated with values

### ISSUE THREAD

**Issue by mdsnor** [NINAnor/NOFAInsert#13]
Users shouldn't be able to create multiple occurrences without values

**Comment by JakobMiksch** [comment]
We could add [here  ](https://github.com/NINAnor/NOFAInsert/blob/master/nofa_insert.py#L2640) something like


```
if lastOccurenceIsEmpty():
       showWarning()
       return
else:
       createNewOccurence()
```

**Comment by mdsnor** [comment]
yes, something like that pseudocode. remember pep8, and the fact that methods of a class shouldn't be camelCase...
