### ISSUE TITLE
Provide documentation pressing the ? help button

### ISSUE THREAD

**Issue by mdsnor** [NINAnor/NOFAInsert#17]
a User Guide for the plugin

* [ ]  a simple "recipe" as PDF - "How to use the plugin?"
* [ ]  maybe a video (should not be to complicated to make it ... )
* [ ] available both in English and Norwegian

**Comment by JakobMiksch** [comment]
We could use the wiki function of this repository or the wiki of this repository: https://github.com/NINAnor/NOFA/wiki

**Comment by svoboond** [comment]
I think online documentation would be better.

It is quite easy to create a website in [Sphinx](http://www.sphinx-doc.org/en/stable/rest.html).
[Online documentation](https://ctu-geoforall-lab-projects.github.io/dp-svoboda-2017/index.html) of the plugin I made for my thesis could be used as an inspiration (in Czech though).
