### ISSUE TITLE
Store Reference and dataset metadata in QSettings

### ISSUE THREAD

**Issue by mdsnor** [NINAnor/NOFAInsert#18]
Reference and Dataset metadata are not likely to be changed frequently. Could be convenient for a user to retrieve the last reference and dataset record used at next plugin start.

**Comment by ninsbl** [comment]
@svoboond This is fixed, right? I suggest closing it...

**Comment by svoboond** [comment]
@ninsbl again it is not closed because the branch I am working on hasn't been merged to master yet.
