### ISSUE TITLE
Deploy on vm-srv-finstad

### ISSUE THREAD

**Issue by ninsbl** [NINAnor/NOFAInsert#19]
There is a NOFAPlugins repository on http://vm-srv-finstad.vm.ntnu.no/NOFA_plugins/
It would make it more convenient for users if they could update the plugin from there.

If you ssh to that server you can automatically deploy the plugin using the script below.
The script could be improved to take command line arguments....

```
vn=0.2
v=${vn}-alpha

cd /var/www/html/NOFA_plugins
wget https://github.com/NINAnor/NOFAInsert/archive/v${v}.zip
unzip v${v}.zip -d ./
mv NOFAInsert-${v} NOFAInsert
zip -r NOFAInsert.zip NOFAInsert
ln=$(grep -n -e "Insert fish occurrence data to NOFA DB" plugins.xml | grep about | awk -v IFS=':' '{print $1 + 1}')
sed -i "${ln}s/.*/        <version>${vn}<\/version>/" plugins.xml

```

**Comment by mdsnor** [comment]
Ok, thanks!

**Comment by ninsbl** [comment]
Should be actually:

```
vn=0.3
v=${vn}-alpha

cd /var/www/html/NOFA_plugins
wget https://github.com/NINAnor/NOFAInsert/archive/v${v}.zip
unzip v${v}.zip -d ./
mv NOFAInsert-${v} NOFAInsert
zip -r NOFAInsert.zip NOFAInsert

ln=$(grep -n -e 'plugin_id="99998"' plugins.xml | cut -f1 -d':')
sed -i "${ln}s/.*/    <pyqgis_plugin name=\"NOFAInsert\" version=\"${vn}\" plugin_id=\"99998\">/" plugins.xml
ln=$(grep -n -e "Insert fish occurrence data to NOFA DB" plugins.xml | grep about | awk -v IFS=':' '{print $1 + 1}')
sed -i "${ln}s/.*/        <version>${vn}<\/version>/" plugins.xml
```
Maybe possible to run this via ssh from development box?
Include it a s a deployment script in the plugin?

**Comment by JakobMiksch** [comment]
This might help https://gis.stackexchange.com/questions/135859/is-it-possible-to-set-up-a-local-qgis-plugin-repository
https://gis.stackexchange.com/a/79950/52597

**Comment by ninsbl** [comment]
http://vm-srv-finstad.vm.ntnu.no/NOFA_plugins/ is already a QGIS plugin repository.

The only remaning thing is to send the released version there, e.g. with the script above...
That would make testing more easy and users would get information about plugin updates...

**Comment by svoboond** [comment]
@ninsbl why isn't there a download url that points at the newest version? Something like https://codeload.github.com/NINAnor/NOFAInsert/zip/master.

**Comment by ninsbl** [comment]
That might be a good solution. However, as long as the meta data is not updated, new plugin versions will not be recognized by the plugin manager at client side.
Furthermore, Jakob/Matteo created releases in github.

Therefore the upload script, but it might be sufficient to just alter the metadata in the repository ... Feel free to change all this as you prefer!

**Comment by svoboond** [comment]
Procedure of how to change a plugin version in [NINA QGIS plugin repository](http://vm-srv-finstad.vm.ntnu.no/NOFA_plugins/plugins.xml) is described in [documentation](https://ninanor.github.io/NOFAInsert/developer-manual.html#nina-qgis-plugin-repository). Closing.
