### ISSUE TITLE
Remove any "test" insertion in db

### ISSUE THREAD

**Issue by mdsnor** [NINAnor/NOFAInsert#20]
Currently, for testing purposes, all new records are fake labeled (in a chosen "host" column) with a "test" string. The code responsible for that need to be removed before going to production. Test records should be removed too (unless testing fase is completed in the nofa_sandbox).

**Comment by ninsbl** [comment]
Should be done by resetting the sandbox. @mdlux I assume this can be closed?

**Comment by JakobMiksch** [comment]
The plugin already works on a new sandbox called "nofa_sandbox_plugin_2017-07-12"

**Comment by ninsbl** [comment]
OK, closing... Feel free to reopen if needed.
