### ISSUE TITLE
modify organism Quantity Vocabulary

### ISSUE THREAD

**Issue by mdsnor** [NINAnor/NOFAInsert#22]
As discussed, need to be changed based on corresponding issue in NOFA repo:

https://github.com/NINAnor/NOFA/issues/3

Using selected terms from this vocabulary:

http://rs.gbif.org/vocabulary/gbif/quantity_type_2015-07-10.xml

**Comment by JakobMiksch** [comment]
is this actually an issue of the plugin or of the database schema?

**Comment by ninsbl** [comment]
Isn't this fixed too?

**Comment by svoboond** [comment]
Yes, AFAIU this has been resolved. Closing.
