### ISSUE TITLE
Yet another Unicode issue...

### ISSUE THREAD

**Issue by ninsbl** [NINAnor/NOFAInsert#25]
When clicking "confirm" in the confirmation dialog I get the following error message with species like "Ørret" or "Ål" (switching to latin names might make a fix unnecessary):

An error has occurred while executing Python code: 

UnicodeEncodeError: 'ascii' codec can't encode character u'\xd8' in position 0: ordinal not in range(128) 
Traceback (most recent call last):
  File "C:\Users\stefan.blumentrath\.qgis-custom/python/plugins\NOFAInsert\nofa_insert.py", line 1330, in preview
    newitem = QTableWidgetItem(str(item))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd8' in position 0: ordinal not in range(128)

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.0 Las Palmas, 0332f5a

**Comment by mdsnor** [comment]
Unicode errors are mysterious to me. I'm not having it.

**Comment by mdsnor** [comment]
Should be fixed by switching to Latin Scientific Names. see issue #26 and #30
