### ISSUE TITLE
Make plugin window a bit bigger or resizable

### ISSUE THREAD

**Issue by ninsbl** [NINAnor/NOFAInsert#28]
On my screen many widgets don`t show everything because the plugin window is to small...
Esp. samplingProtocoll drop down and Add dataset button lack space

![image](https://cloud.githubusercontent.com/assets/4246620/24551448/c1e373d4-1622-11e7-8624-67dcf7d675dd.png)

**Comment by JakobMiksch** [comment]
UI has some limitations on Ubuntu (OSGeoLive 10.5)
* Names are cut
* Dropdown menu too thin 


![image](https://cloud.githubusercontent.com/assets/15704517/26104921/337b2564-3a40-11e7-9c27-c2e784e806ee.png)

**Comment by ninsbl** [comment]
Seems to be fixed in @svoboond `s branch on my Windows PC.
Closing this issue. Feel free to re-open if it is still a problem on other platforms...
