### ISSUE TITLE
Remove @ from project and reference drop down

### ISSUE THREAD

**Issue by ninsbl** [NINAnor/NOFAInsert#29]
There is an unneccessary @ in the drop down menu...

**Comment by JakobMiksch** [comment]
What else shall be used as separator? Maybe just a normal whitespace? Or maybe a "-" ?
![image](https://cloud.githubusercontent.com/assets/15704517/25706795/be22a06a-30e1-11e7-9fce-36b5c5fef4db.png)

**Comment by ninsbl** [comment]
"-" looks very good! Does not even need white space around, so it can be short. A simple, single space would also be a good delimiter. Single space is my favorite actually (even if also present in the dataset name), but I have no strong opinion.

**Comment by JakobMiksch** [comment]
I created a branch about this issue where the "@"-sign is removed: db53978ec2251b0cf2fe17824007fe7fbb43a53f 
You can try it. I am happy about feedback

**Comment by JakobMiksch** [comment]
merged into beta db53978ec2251b0cf2fe17824007fe7fbb43a53f
