### ISSUE TITLE
add icons to "add" and "delete occurence"

### ISSUE THREAD

**Issue by JakobMiksch** [NINAnor/NOFAInsert#32]
"add" and "delete occurence" could be replaced by icons with a garbage can or a plus

![image](https://cloud.githubusercontent.com/assets/15704517/25666377/afca7b30-3020-11e7-8962-907a75b90f62.png)

We could use the icons from [Mapbox Maki](https://www.mapbox.com/maki-icons/)
They are under CC0 licence

![image](https://cloud.githubusercontent.com/assets/15704517/25666956/50d2a7c2-3022-11e7-95c7-bf110110ac86.png)

**Comment by ninsbl** [comment]
Yes, very good! And it might free some space if these buttons were under the arrows (and the arrows were a bit smaller - less high).

**Comment by JakobMiksch** [comment]
I finally used text rather than icons. 

![image](https://cloud.githubusercontent.com/assets/15704517/25695890/32401bbc-30b5-11e7-93ee-f5c219daec85.png)

**Comment by ninsbl** [comment]
Very good!
