### ISSUE TITLE
ecotype selection error 

### ISSUE THREAD

**Issue by mdsnor** [NINAnor/NOFAInsert#33]
After selecting an ecotype for one of the species which has an ecotype (example: salmo salar), even if I delete that occurrence row, creating a new occurrence row it is possible to select the ecotype related to the previous update. Should be switching to the initial situation of not available ecotype for a new one.

**Comment by JakobMiksch** [comment]
@mdlux I cannot reproduce that

**Comment by JakobMiksch** [comment]
I found a error:
![image](https://cloud.githubusercontent.com/assets/15704517/25909015/205c08d8-35ac-11e7-9e1f-4ca677ec140d.png)

Now there is a date in the ecotype field. This should be fixed.

This effect happens, when I change any field of the row above.

**Comment by ninsbl** [comment]
Fixed in latest plugin version. Closing the issue. Feel free to reopen if needed.
