### ISSUE TITLE
Use library for creating SQL statements

### ISSUE THREAD

**Issue by JakobMiksch** [NINAnor/NOFAInsert#37]
The SQL statements could be build with a library. This would maybe increase the readability of the code. These links might be useful:
* https://pypi.python.org/pypi/sqlbuilder 
* http://www.sqlalchemy.org/ 
* https://ponyorm.com/

**Comment by mdsnor** [comment]
psycopg2 is just a database connector, and the query are built in SQL. SQL is widely known, and quite readable, for those who know it. Probably much more people reading SQL than python out there. A library for building queries could look appealing, but I would rather stay with a better known, widely used and documented library as psycopg2. Maybe could be worth trying the library for smaller scripts, but in the context of the current plugin, it would be an unnecessary and time consuming refactoring. Just my opinion...

**Comment by JakobMiksch** [comment]
As far as I understood [sqlbuilder](https://pypi.python.org/pypi/sqlbuilder) simply helps to create a string with a SQL statement. So, we would still send an SQL string to psycopg2, like we did before. The only difference is that building the SQL strings would be a bit cleaner. But, I totally agree, that is not crucial. I just wrote it down as an idea.

**Comment by svoboond** [comment]
I agree with @mdlux. Right now everything related to database is stored in [database](https://github.com/NINAnor/NOFAInsert/blob/master/nofa/db.py) module that works with psycopg2.
