### ISSUE TITLE
Improve UI for adding new locations

### ISSUE THREAD

**Issue by JakobMiksch** [NINAnor/NOFAInsert#45]
* [x] So far, multiple locations can be added using comma-separated string. It would be nice to add them via a table.
* [x] Add new locations from the map (canvas), or the lake/rivers layers, by mouse click
* [x] rework location GUI

**Comment by JakobMiksch** [comment]
#48 is related

**Comment by mdsnor** [comment]
And also:
* [ ] Add new locations from the map  (canvas), or the lake/rivers layers, by mouse click?

**Comment by JakobMiksch** [comment]
@mdlux I added your suggestion to the issues explanation on the top

**Comment by ninsbl** [comment]
Also fixed or duplicated? Can we close this?

**Comment by svoboond** [comment]
TBH there are quite few issues that somehow similar. The whole GUI for selecting and adding locations must be reworked.

**Comment by svoboond** [comment]
Location GUI has been reworked.

I edited OP because as mentioned there is another issue for preview.
