### ISSUE TITLE
Event: Change order of "sampleSizeValue" and "sampleSizeUnit" fields

### ISSUE THREAD

**Issue by JakobMiksch** [NINAnor/NOFAInsert#51]
the fields "sampleSizeValue" and "sampleSizeUnit" should be switched:

![image](https://cloud.githubusercontent.com/assets/15704517/26001080/7908d33c-372b-11e7-88d7-7dfade92e0ad.png)

This would be more logical.

**Comment by ninsbl** [comment]
Not sure why this issue was not closed through @svoboond `s commit. But it is switched in the latest version of the plugin.

**Comment by svoboond** [comment]
@ninsbl I think it is because I closed this issue in a branch that is not master.
