### ISSUE TITLE
Update plugin to new data base schema

### ISSUE THREAD

**Issue by JakobMiksch** [NINAnor/NOFAInsert#52]
Our "sandbox" db must be upgraded to the "original" NOFA database. Then we have to update our plugin accordingly. This will probably raise a lot of new issues.

**Comment by svoboond** [comment]
I am working on this in branch [db-nofa_sandbox_plugin_2017-07-12](https://github.com/NINAnor/NOFAInsert/tree/db-nofa_sandbox_plugin_2017-07-12). Currently it is possible to add a new dataset, project or reference and inserting into NOFA database also works.

**Comment by svoboond** [comment]
With the latest merge the master branch is working with database "nofa_sandbox_plugin_2017-08-08". This database is up-to-date with the production database.
