### ISSUE TITLE
"Clear Everything"-Button

### ISSUE THREAD

**Issue by JakobMiksch** [NINAnor/NOFAInsert#53]
We need a button that clears the whole form. This is necessary if someone wants to enter multiple events.

**Comment by ninsbl** [comment]
Is this fixed with https://github.com/NINAnor/NOFAInsert/commit/5e2b94e5dbeca5911a7370a55d86f08ac1c4c1bb ?

**Comment by svoboond** [comment]
@ninsbl I am not entirely sure what "entire form" means.

In https://github.com/NINAnor/NOFAInsert/commit/5e2b94e5dbeca5911a7370a55d86f08ac1c4c1bb I added a button that resets all rows in the occurrence table but it does not reset location, event, dataset, project and reference.

If this is considered as "entire form" then the issue fixed.

**Comment by mdsnor** [comment]
No, it is not. It should be a button which allows starting to work to a completely new event of data insertion. Maybe dataset, project and reference could be kept, in case they are the same (easy to be changed)
