### ISSUE TITLE
Separate UI functionality and NOFA Connection

### ISSUE THREAD

**Issue by JakobMiksch** [NINAnor/NOFAInsert#55]
So, far all the logic is inside the [nofa_insert.py](https://github.com/NINAnor/NOFAInsert/blob/master/nofa_insert.py) file. Hence, the functionality can only be used by clicking through the UI. This makes it difficult to debug. 

It would be nice to have an independent python class (e.g. event.py) that stores all information from one event and provides methods to upload them to NOFA. It could be used as a command line program or as a Python library. This would make it much easier for debug.

The NOFAInsert would simply be a GUI for this class. Moreover, it would be very easy to reuse it in any other Python application (e.g. Django)

**Comment by JakobMiksch** [comment]
When I try to solve an issue, I both have to deal both with the UI and the data inserterion to NOFA. It would be much easier to focus on only one thing. Moreover, this would make the code more understandable and maintainble ...

Making the plugin more modular would take some more time. But I think it would pay off, since it would be so much easier to debug and maintain it in future.

**Comment by ninsbl** [comment]
@svoboond is this something you could imagine to work on? Or did you even already do something in this direction?

**Comment by svoboond** [comment]
@ninsbl this is already solved in the branch [db-nofa_sandbox_plugin_2017-07-12](https://github.com/NINAnor/NOFAInsert/tree/db-nofa_sandbox_plugin_2017-07-12) am working on. I created a package called "[nofa](https://github.com/NINAnor/NOFAInsert/tree/db-nofa_sandbox_plugin_2017-07-12/nofa)". In that package there is a module called "db" with everything related to the database and another package called "gui" with modules that work with GUI.

**Comment by ninsbl** [comment]
Great! Does it men we can close this issue?

**Comment by svoboond** [comment]
Yes, I think so but once again I would close this issue when the branch where it is fixed is merged with master.

**Comment by svoboond** [comment]
Fixed with merge.
