### ISSUE TITLE
Move the log tables from the nofa schema to a new one, specific for the plugin

### ISSUE THREAD

**Issue by mdsnor** [NINAnor/NOFAInsert#56]
![image](https://cloud.githubusercontent.com/assets/10074798/26346424/7eac43b8-3fa6-11e7-9709-f3087f664ee2.png)
We have to move to a new schema of the nofa db the log tables, which exist only in the nofa_sandbox db.
The new schema will only contain tables strictly related to the plugin.

**Comment by JakobMiksch** [comment]
@mdlux Shall the "logging"-schema be both in the sandbox and in the productive database?

**Comment by ninsbl** [comment]
Yes, we have to add them to the production database. See also the question from @svoboond per mail.

@mdlux I assume you have the SQL code for generating the tables somewhere?

**Comment by svoboond** [comment]
I created the log tables by a script Matteo gave me. The tables are now in both "nofa" and "nofa_sandbox_plugin_2017-07-12" databases.
