### ISSUE TITLE
Change metadata tab heading (order)

### ISSUE THREAD

**Issue by ninsbl** [NINAnor/NOFAInsert#60]
In metadata tabs use the following information in the header in the following order:

Dataset:
Dataset name

Project:
Project name, Organization

Reference:
Author, year, title

**Comment by svoboond** [comment]
@ninsbl by the headers you mean only the names of the metadata tabs or should I also change text in the combo boxes?

**Comment by ninsbl** [comment]
@svoboond I only meant the tam names. So this seems fixed. Thanks! I leave closing the issue to you.

**Comment by svoboond** [comment]
Fixed with merge.
