### ISSUE TITLE
organismQuantityType, occurrenceStatus and population trend can not be entered

### ISSUE THREAD

**Issue by ninsbl** [NINAnor/NOFAInsert#61]
organismQuantityType, occurrenceStatus and population trend can not be entered

**Comment by svoboond** [comment]
I would not call this a bug because it could not be entered in the old version either.

**Comment by svoboond** [comment]
@ninsbl so you want to make it possible for user to add a new organismQuantityType/occurrenceStatus/populationTrend via GUI? Are there any resctrictions of what user can add?

**Comment by ninsbl** [comment]
For a full DB front end, modifying the lookup tables would also be necessary. But that is something we should keep for later.

Here I meant that comboboxes for occurrenceStatus and populationTrend are empty. 
organismQuantityType seems to be OK, so this was my bad (though we might have to check the content of the DB table)...

**Comment by svoboond** [comment]
@ninsbl what database are you connected to? I tested "nofa" "nofa_sandbox_plugin_2017-07-12" databases and both occurrenceStatus and populationTrend combo boxes are populated.

**Comment by ninsbl** [comment]
That was it. I was connected to nofa_sandbox... Works all fine!
