### ISSUE TITLE
Add <all> option to location filters

### ISSUE THREAD

**Issue by svoboond** [NINAnor/NOFAInsert#65]
Add option to search for locations in all countries/counties/municipalities.

**Comment by ninsbl** [comment]
Maybe we should allow for multiple input in the filter combo boxes!? What do you think @andersfi 

One might have e.g. data from two or three counties or several municipalities or the like...

Filtering like that is also implemented in the Visualisation plugin BTW. See:
https://github.com/NINAnor/invafish/tree/master/QGIS_plugin/NOFAVisualisation

**Comment by svoboond** [comment]
@ninsbl that is a good idea. I created a new issue for that https://github.com/NINAnor/NOFAInsert/issues/69.
