### ISSUE TITLE
When adding locations from a list of coordinates (or VatlNr), allow users to preview them

### ISSUE THREAD

**Issue by mdsnor** [NINAnor/NOFAInsert#71]
To avoid mistakes, a button (or similar solution) should allow users to preview the location names, and maybe visualize them on canvas, before adding to the db.

**Comment by ninsbl** [comment]
Isn't that the way results from the water body search are treated already, except that coordinates  can add  new locations... Maybe possible to consolidate into one unified solution for all supported ways to enter or select locations?

**Comment by ninsbl** [comment]
See also #45 and  #48
