### ISSUE TITLE
Save taxonomic coverage into database

### ISSUE THREAD

**Issue by svoboond** [NINAnor/NOFAInsert#72]
Information about taxonomic coverage is currently not used. User can check taxonomic coverage items but it is not inserted into the database.

Please provide an example insert so I could implement it.

**Comment by andersfi** [comment]
Term is called samplingTaxaRange in DB (event table). See e.g. "datasetID"='NORS' for examples on usage. Currently, this is implemented as an array of taxonID's. 

We are not quite happy with this solution as postgres does not provide any means to have FK constraints for arrays and consistency would depend upon user input, and there is no quick fix if changing taxonIDs in the future. However, it it what it is at the moment, and the term is rather important as it gives a mean of recording absence data without filling the occurrence table with records(rows) of occurrrenceStatus='absent'. e.g. the before-mentioned dataset (NORS) would increase the numbers of occurrence records many times. 

Please note that the samplingTaxaRange variable is placed on the event level (event table term), and therefore could be shown / hidden along with the rest of the event terms for consistency. 

A.

**Comment by ninsbl** [comment]
There is already a normalized table taxonomicCoverage for that purpose that has to be renamed (also the respective column) to the proper dwc term Anders mentioned.
We did not put the widget into the event tab due to size issues.

**Comment by svoboond** [comment]
Table nofa."taxonomicCoverage" has been changed according to your comments.

```
ALTER TABLE	nofa."taxonomicCoverage"
RENAME TO	"samplingTaxaRange";

ALTER TABLE	nofa."samplingTaxaRange"
RENAME		"eventID_observationEvent_serial" TO "id";

CREATE SEQUENCE	nofa."samplingTaxaRange_id_seq";

ALTER TABLE	nofa."samplingTaxaRange"
ALTER COLUMN	"id" SET DEFAULT nextval('nofa."samplingTaxaRange_id_seq"');

ALTER TABLE	nofa."samplingTaxaRange"
RENAME		"taxonID_l_taxon" TO "taxonID";

ALTER TABLE	nofa."samplingTaxaRange"
RENAME		"eventID_observationEvent" TO "eventID";

ALTER TABLE	nofa."samplingTaxaRange"
ALTER COLUMN	"eventID" SET NOT NULL;

ALTER TABLE		nofa."samplingTaxaRange"
RENAME CONSTRAINT	"l_taxon_fk" TO "samplingTaxaRange_fk_taxonID";

ALTER TABLE		nofa."samplingTaxaRange"
RENAME CONSTRAINT	"observationEvent_fk" TO "samplingTaxaRange_fk_eventID";

ALTER TABLE	nofa."samplingTaxaRange"
DROP CONSTRAINT	"samplingTaxaRange_pkey";

ALTER TABLE	nofa."samplingTaxaRange"
ADD CONSTRAINT	"samplingTaxaRange_pkey" PRIMARY KEY(id, "taxonID", "eventID");
```

**Comment by svoboond** [comment]
I messed up the primary key. Here is the fix.

```
ALTER TABLE	nofa."samplingTaxaRange"
DROP CONSTRAINT	"samplingTaxaRange_pkey";

ALTER TABLE	nofa."samplingTaxaRange"
ADD CONSTRAINT	"samplingTaxaRange_pkey" PRIMARY KEY(id);
```
