### ISSUE TITLE
Enable swithcing / viewing of database connection from pluggin interface? 

### ISSUE THREAD

**Issue by andersfi** [NINAnor/NOFAInsert#75]
Is is possible to switch database from the pluggin itself? At least be able to see what database one is connected to somewhere would be nice (or maybe I missed it?). 
A.

**Comment by ninsbl** [comment]
Maybe not that relevant for the common user and production. But at least visualizing the db name e.g. in header of the window should not be a big deal...

**Comment by mdsnor** [comment]
Svoboond already worked on it,but it is not in the main plugin window. you find it under the Plugins TAB -> NOFAInsert -> Connection Parameters. It is also possible to change connection to a different DB

**Comment by svoboond** [comment]
Together with @mdlux we decided not to put additional button into GUI. You can still access that window as described.

**Comment by svoboond** [comment]
Database name has been added to the dialog title.

@andersfi Should I add a button to the main dialog that would open a connection dialog?

**Comment by ninsbl** [comment]
I would agree that we should not add such a button to the data input UI to not overload it. Switching db is a rarely used operation. For me it would be sufficient to see which db  I am connected to...

**Comment by andersfi** [comment]
Agree with @ninsbl on that, however, it would be good to know how to switch db. There are obvious uses for sandbox environments in e.g. training. Maybe this is a documentation issue, not a interface issue?

**Comment by svoboond** [comment]
AFAIK currently there is no documentation for the plugin. I think this issue has already been solved.

There is an issue #17 to create a documentation.
